### ISSUE TITLE
Support Sentry like with RQ 

### ISSUE THREAD

**Issue by gkieninger** [django-commons/django-tasks-scheduler#155]
**Is your feature request related to a problem? Please describe.**
I would like to use sentry for catching errors while background tasks are running

**Describe the solution you'd like**
I would like to be possible to pass this to the worker
https://docs.sentry.io/platforms/python/integrations/rq/
rq worker \
    -c mysettings \  # module name of mysettings.py
    --sentry-dsn="https://1ed363f4613e4fd6980f7a2ab8ca6aa7@o173429.ingest.us.sentry.io/1399287"  # only necessary for RQ < 1.0

**Describe alternatives you've considered**
-
**Additional context**

**Comment by gabriels1234** [comment]
@gkieninger is this enhancement only beneficial for thouse using RQ < 1.0? then it's not compatible with this
`rq = "^1.16"` is mentioned.
