### ISSUE TITLE
Add --worker-class argument to rqworker

### ISSUE THREAD

**Issue by gabriels1234** [django-commons/django-tasks-scheduler#164]
Hi @cunla !
Following along with --job-class another feature present in [RQ](https://python-rq.org/docs/workers/) for workers is to provide the --worker-class. In order to keep everything in place, the worker must also be a DjangoWorker

I need to introduce a Custom Worker (to do some shutdown handling to play along AWS spot-instances)

**Describe the solution you'd like**
`rqworker default --worker-class myproj.customDjangoWorker`

**Describe alternatives you've considered**
I tried to implement the functionality directly by calling rq commands (do handle SIGTERM) but that would have unintended consequences.

**Additional context**
I would consider implementing all the rq worker args. Maybe introduce them in order of need.

**Comment by cunla** [comment]
Hi,

Thank you for your suggestion. However, I'm hesitant to add further customization options. While I approved the addition of job-class, it was done with some reservations. Introducing more flexibility brings up numerous questions: Should job-class be defined per queue, per worker, per task, or per job? This complexity goes against the core philosophy of this package, which is simplicity and ease of use.

If you're seeking a higher level of customization, I would suggest considering Celery, which is designed for more flexible (yet complex) use cases.

For your specific scenario, I recommend creating a new management command that instantiates your worker class, which can inherit from DjangoWorker. This will give you the control you need without adding unnecessary complexity to the package.

**Comment by gabriels1234** [comment]
@cunla Thanks for the idea. Would you like me to create a new PR for the JobExecution pieces of this PR?
I wanted to keep a tighter cohesion with rq, which supports --worker-class, because this project is the go-to instead of django_rq, and I think it's where most of the usage comes from.

**Comment by cunla** [comment]
I aim to detach as much as possible from rq. If I had more time, I would have done it already :)

I am not sure whether this package is right for you considering you want the rq cohesion. You are, of course, welcome to fork it and maintain it as you like (I would appreciate keeping the license credits though).

**Comment by gabriels1234** [comment]
@cunla

That would be great!

I ended up following your advice and adding rqworker_alt.py command that allows for the Worker class.

Back to RQ-compatibility What would be the best way to proceed regarding forking this repo and maintaining it? What do you suggest regarding pypi?

**Comment by cunla** [comment]
- Fork the repo
- Make sure all the github workflows are working as expected (Particularly, you need to have `GIST_SECRET` set to make sure coverage results are posted, but you can remove this step if you like as well).
- update pyproject.toml with a new package name, etc.
- update publsh.yml to publish to your package name.
