### ISSUE TITLE
broker will only use redis when sentinel is set

### ISSUE THREAD

**Issue by amirreza8002** [django-commons/django-tasks-scheduler#189]
[as you can see here](https://github.com/django-commons/django-tasks-scheduler/blob/master/scheduler/queues.py#L66) if user has set up a sentinel broker, redis sentinel will be imported and used.

now, since only valkey and redis are officially supported, and they are, for the moment, interchangable, this won't break anything; but it has the potential to break in the future.

and perhaps `_get_redis_connection` isn't the best name either.

also you officially support valkey but barely mention it in your docs, and projects description only mentions redis.

**Comment by cunla** [comment]
That's a good point! the valkey support is very recent and I haven't addressed all aspects yet since I am focusing on redesigning the model.

Would you want to contribute to the package?

**Comment by amirreza8002** [comment]
hi
more than happy to 

tho i need to ask:
are redis and valkey packages going to remain required? or change to be extra?

i can change the imports to use `try/except` as well

**Comment by cunla** [comment]
- At least for the foreseeable future, `rq` dependency will remain, and therefore, `redis-py` does not need to be explicitly mentioned in the dependencies.
- Making `valkey-py` optional makes sense - this will allow users to opt out of having it. Though this means a layer of abstraction would be needed. Are you up for implementing that?

**Comment by amirreza8002** [comment]
I'm a bit vague on what you mean

if you agree I'll set up a draft PR in a day or two, perhaps having the conversation over existing code would be easier

**Comment by cunla** [comment]
I updated the PR and merged it.
I also updated the project description.
Please feel free to contribute to the code/documentation.
