### ISSUE TITLE
Support for Custom Queues in Django 4.2 with django-tasks-scheduler

### ISSUE THREAD

**Issue by DhavalGojiya** [django-commons/django-tasks-scheduler#200]
We are currently migrating one of our client projects from **Django 2.2** to **Django 4.2 LTS**.  
Directly upgrading to Django 5.x is not feasible due to the significant gap between Django 2.2 and Django 5.x. Furthermore, Django 4.2 is the latest LTS version, and the client's recommendation is to upgrade only to **Django 4.2 LTS**.

Our project currently uses the following packages:
- `django_rq`
- `rq`
- `rq_scheduler`

To run tasks, we typically execute two commands:
1. **Start Worker** (_django_rq package_):  
   ```bash
   python manage.py rqworker high
   ```
2. **Start Scheduler** (_rq_scheduler package_):  
   ```bash
   python manage.py rqscheduler --queue=high
   ```

---

### Migration Challenges

We are considering migrating from `rq_scheduler` to this `django-tasks-scheduler` package. The package offers a beautiful admin dashboard and simplifies operations by allowing us to use a single command to start both the worker and the scheduler simultaneously:  

```bash
python manage.py rqworker high --with-scheduler
```  

#### Our Challenges:
1. **Django Compatibility**  
   The latest versions of `django-tasks-scheduler` (v2.x) only support **Django 5.x**.

2. **Queue Configuration**  
   Versions `v1.3.3` and `v1.3.4` of `django-tasks-scheduler` have hardcoded choices for queues in the model and do not use custom queues defined in Django settings. (Refer to [[Issue #152](https://github.com/django-commons/django-tasks-scheduler/issues/152#issuecomment-2379956203)](https://github.com/django-commons/django-tasks-scheduler/issues/152#issuecomment-2379956203).

---

### Potential Solution

The only viable version for our use case is **`django-tasks-scheduler` v1.3.2**, as it:
- Supports Django 4.2.
- Works with `rq` versions below 2.0.  
  To accommodate this, we plan to:
  - Downgrade `django_rq` from `v3.0.0` to `v2.10.0` (compatible with `rq<2.0`).
  - Use `rq==1.16.2`, which is supported by both `django_rq` and `django-tasks-scheduler`.

---

### Request for Suggestions

Can you recommend any other alternatives for our use case?  

Alternatively, is there a way to adapt `django-tasks-scheduler` **v1.3.4** (latest in the v1.x series) to support:
- Custom queue configurations (defined in Django settings)?

We appreciate any insights or guidance you can provide.

**Comment by cunla** [comment]
Hi,

When using django-tasks-scheduler, AFAIK, you don't really need django-rq or rq_scheduler.
As far as django-tasks-scheduler versions, you are right, you need the latest v1.x since v2 dropped support for django v4.

Note: Starting v3 of django-tasks-scheduler, the models will be changed (See latest beta versions) and there won't be a need for `rq` package as well.

**Comment by DhavalGojiya** [comment]
Oh, I see! If we want to use `django-tasks-scheduler`, there will be no need for `rq_scheduler` or `django_rq`.  

It's good to know that `django-tasks-scheduler` only requires the low-level `rq` Python library for queueing jobs and processing them in the background with workers. It's even better to hear that this `rq` dependency will also be dropped starting from version 3.x of `django-tasks-scheduler`.

Now I have a question:  
I went through the `django-tasks-scheduler` documentation and found the following command to run a worker:

```python
python manage.py rqworker high notification
```
This starts the worker for two queues: high and notification. 

But what about the scheduler? Do we also need to start a scheduler? If so, how is it handled in django-tasks-scheduler?
Is there any specific flag or option with the python manage.py rqworker command to start the scheduler as well?

**Comment by cunla** [comment]
the worker has a scheduler by default.

**Comment by DhavalGojiya** [comment]
Thank you @cunla.
Got it.
